apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-queue:release1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-similator
spec:
  selector:
    matchLabels:
      app: position-similator
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: position-similator
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env:
          - name: SPRING_PROFILE_ACTIVE
            value: production-microservice
